---
  # Run for these hosts in inventory file
  # Do not become root
- hosts: all
  become: no

  # Run these tasks
  tasks:

  # Named task
  - name: list ~/bin directory.
    command: >
      ls ~/bin
    register: result
  - debug: var=result['stdout_lines']

