---
  # Run for these hosts in inventory file
  # Do not become root
- hosts: link.local
  become: no

  # Run these tasks
  tasks:

  # Named task
  # Use command: for simpler scripts, preferred over shell: when possible.
  - name: run ~/bin/rsysinfo.
    command: > 
        ~/bin/rsysinfo

    register: result
  - debug: var=result['stdout_lines']

